### ISSUE TITLE
[FEAT] Add support for arbitrary properties at the BOM level (`bom.properties`)

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#125]
As identified in #67, this library does not yet support properties at the `bom` root level.

This feature will add support to allow a BOM to have properties.

**Comment by madpah** [comment]
Blocked waiting on https://github.com/CycloneDX/specification/issues/130

**Comment by madpah** [comment]
The upstream specification fix has been accepted for CycloneDX v1.5.

**Comment by jkowalleck** [comment]
:warning:  implementation detail: 
when serializing for CDX 1.4 JSON, this must not be rendered,
Because schema 1.4 is in strict mode and does not allow undeclared elements.

in schema 1.3 it would be okay to render the elements, as is is not strict per default - CDX 1.3 allows additional properties/elements.
