### ISSUE TITLE
[FEATURE] When a BOM is generated with zero Components, `components` is still present in the generated BOM

### ISSUE THREAD

**Issue by madpah** [CycloneDX/cyclonedx-python-lib#147]
Very minor issue noted here.

If a BOM is has ZERO Components, `components` is still included in the generated BOM as an empty array.

Not invalid, but not tidy.

**Comment by jkowalleck** [comment]
not a bug, but a feature... and a requirement.

an a requirement for CycloneDX  spec 1.0 requires the presence of `bom.components`  
see https://github.com/CycloneDX/specification/blob/ccbf7b5781ef534cd62616e3c4221004c7c82a66/schema/bom-1.0.xsd#L215

an a requirement for CycloneDX  spec 1.1 requires the presence of `bom.components`  
https://github.com/CycloneDX/specification/blob/ccbf7b5781ef534cd62616e3c4221004c7c82a66/schema/bom-1.1.xsd#L687

since spec 1.2 `bom.components` is optional
see https://github.com/CycloneDX/specification/blob/ccbf7b5781ef534cd62616e3c4221004c7c82a66/schema/bom-1.2.xsd#L1360

**Comment by madpah** [comment]
Good call @jkowalleck - easiest to leave in then would you say?

**Comment by jkowalleck** [comment]
if this feature was implemented,
i would expect to have unit/integration tests that generate a BOM with empty components list and actually normalize the data to XML 
and then validate the resulting XML with the known schema.
SO there should be one test for XML spec 1.0, one for ... , and one for 1.4 
SO there should be one test for JSON spec 1.2, one for ... , and one for 1.4 

----

@madpah dont know. This fix/feature does not actually change the resulting data. it is just a different representation.
its a task for rainy weekends, i guess. and a fun one, too.

**Comment by madpah** [comment]
https://pypi.org/project/cyclonedx-python-lib/2.0.0/ released
