### ISSUE TITLE
FORWARD PORTS NEEDED

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-python-lib#332]
since v4 got in dev phase, some fixes were applied to older versions.
these need to be ported forward to the v4

**Comment by jkowalleck** [comment]
- [ ] port forward: #330

**Comment by jkowalleck** [comment]
- [ ] port forward: a solution for #328

**Comment by jkowalleck** [comment]
- [ ] port forward: the mock of `ThisTool.version` in tests - # #335

**Comment by madpah** [comment]
@jkowalleck am reviewing the items you market for forward porting to `4.0.0`:

- #330 - I don't believe this directly applies to the `4.0.0` codebase, and there was no unit test added in the fix for `3.x.x` - could you please review?
- #328 - confirmed as already fixed in `4.0.0`
- #334 - TBC
- #336 (partial - PR #338) - Confirmed included in `4.0.0`

**Comment by madpah** [comment]
Included in `4.0.0` - now released.
