### ISSUE TITLE
Error: Unexpected key lifecycles/lifecycles in data being serialized to cyclonedx.model.bom.BomMetaData

### ISSUE THREAD

**Issue by behnazh-w** [CycloneDX/cyclonedx-python-lib#632]
I am trying to deserialize [the SBOM](https://repo1.maven.org/maven2/org/apache/maven/maven/3.9.7/maven-3.9.7-cyclonedx.json) generated for `pkg:maven/org.apache.maven/maven@3.9.7`. I'm getting a `ValueError` as shown below:

```python
>>> from cyclonedx.model.bom import Bom
>>> import json
>>> f = open("/tmp/sbom.json")
>>> data = f.read()
>>> Bom.from_json(json.loads(data))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/serializable/__init__.py", line 333, in from_json
    _data[k] = prop_info.concrete_type.from_json(data=v)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/serializable/__init__.py", line 301, in from_json
    raise ValueError(
ValueError: Unexpected key lifecycles/lifecycles in data being serialized to cyclonedx.model.bom.BomMetaData
```

I am using `cyclonedx-python-lib@7.4.1`.

**Comment by jkowalleck** [comment]
acknowledged.
this is due to the missing data models for that purpose. see https://github.com/CycloneDX/cyclonedx-python-lib/issues/578 

---

CycloneDX python library is maintained by volunteers, and drive by members of the Community. 
Feel free to contribute the bits and peaces you or your organization needs.
If you plan on doing so, please let us know in a respective github issue or in our [slack channel](https://cyclonedx.slack.com/archives/CVA0QJEVA) ([invite](https://cyclonedx.org/slack/invite))
